### ISSUE TITLE
ExecuteKnownTrajectory not present in humble branch

### ISSUE THREAD

**Issue by aditya2592** [moveit/moveit_msgs#169]
Hi, the file `srv/ExecuteKnownTrajectory.srv` does not seem to be present in the branch `humble` but `move_group` package in `moveit2` repo has this capability that requires it `moveit_ros/move_group/src/default_capabilities/execute_trajectory_service_capability.cpp`

I was not sure if this intentional or just missing

**Comment by mikeferguson** [comment]
This message was removed in favor of ExecuteTrajectory.srv - https://github.com/moveit/moveit2/pull/1836 - looking at the humble branch in moveit2, I don't see any reference to this header
